### Send POST request with json body
POST {{url}}
Content-Type: application/json



{
  "id": "95538bb9-42a9-4601-9a14-179088bbdacb",
  "timestamp": "1697185384678",
  "message": "Ik wil dit ook nog eens opslaan.",
  "username": "Boma worst",
  "token": "eELjRWwfOH-Zyf9uOgr9Ob:APA91bF4tAykQyrP3tr03XX07GIv14f6Z2O_0LiymumMbb9WVGErnrUuU2RtY8P3SCLPAF8JdarGJgZ-H-z4EoNRC4dFxZ2pcFNsBVzBhxdh_oX6PqUnTRIUZJx2KlunicopwA3Wtuy-"
}
