### Send POST request with json body
POST {{url}}
Content-Type: application/json



{
  "id": "ab2e2132-69a1-11ee-8c99-0242ac120002",
  "timestamp": "1697185384688",
  "message": "Ik wil dit ook opslaan.",
  "username": "Boma worst"
}
